general {
    hide_cursor = true
    grace = 0         # seconds before lock engages
    no_fade_in = false
}

label {
    text = $TIME          # built-in variable
    font_size = 128
    color = rgba(255,255,255,0.9)
    position = 0, 80
    halign = center
    valign = center
}

/* label {
    text = $USER
    font_size = 18
    color = rgba(255,255,255,0.6)
    position = 0, 20
    halign = center
    valign = center
} */
